### ISSUE TITLE
AJouter un point de vente

### ISSUE THREAD

**Issue by teliwal** [GolleSobhe/kifiya#14]
En tant qu'Admin je dois pouvoir ajouter un point de vente,
Pour cela je dois indiquer
-Le nom du point de vente
-une indication geographique

Indication technique
Ces informations doivent être ajoutées dans la table BOUTIQUE

**Comment by kikalaSobhe** [comment]
Ne fonctionne pas, quand je clique sur le bouton ajouter j'ai un 404 après qui est dû à des exceptions

**Comment by fiyaHolloSobhe** [comment]
ça marche de mon coté
