### ISSUE TITLE
Ajouter un Gerant

### ISSUE THREAD

**Issue by teliwal** [GolleSobhe/kifiya#15]
En tant qu'Admin je dois pouvoir ajouter un gerant
Pour cela je dois renseigner:
Son nom,prenom,numero de telephone,
Le systeme doit lui generer un identifiant et un mot de passe par defaut
Indications techniques
Ces informations doivent être ajoutées dans la table GERANT

**Comment by kikalaSobhe** [comment]
fonctionne sans connexion pour le moment
