### ISSUE TITLE
page d'accueil générale et harnomisation des container

### ISSUE THREAD

**Issue by mignamayeSobhe** [GolleSobhe/kifiya#49]
C'est la première page qui s'affiche quand l'application est lancée.
Permettre à l'utilisateur de faire une estimation.
Affichage une descriptive de l'application

**Comment by fiyaHolloSobhe** [comment]
@mignamayeSobhe , j'ai echangé avec @kikalaSobhe  sur la page d'accueil, nous avons suggerer de retravailler la page:

- Supprimer le bouton evoyer de l'argent
- Supprimer le fomulaire estimer les frais 
Remplace les deux items ci-dessus par un formulaire avec deux champs, saisier la somme d'argent et un select sur le point de retrait.

En plus il faut rendre la section "Nos principaux points de retraits dynamique" c'est á dire la section ne s'affiche pas s'il ya zero point de vente.
Actuellement aussi en saissaont sur le champ input tu ne vois pas ce que tu saissies au moment de la saisie.
- Rendre la page d'acceuil dynamique
